#!/bin/bash


source qprojenv/bin/activate

if [[ "$1" == "--fetch" ]]; then
    python src/fetch_data.py || python3 src/fetch_data.py
    echo "Data fetched. Now running analysis..."
fi

python src/analyse.py || python3 src/analyse.py
echo "Analysis results have been saved to the out directory."